name: PullRequest Checker

on:
  pull_request_target:
    types:
      - closed
    paths-ignore:
      - 'docs/**'

jobs:
  read_file:
    runs-on: ubuntu-latest
    outputs:
      require-result: ${{ steps.contributors.outputs.content}}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Read contributors.json
        id: contributors
        uses: juliangruber/read-file-action@v1
        with:
          path: ./contributors.json

  check_merged:
    runs-on: ubuntu-latest
    needs: read_file
    if: contains(fromJSON(needs.test_file.outputs.require-result), github.actor) == false && github.event.pull_request.merged == true
    steps:
      - uses: actions-cool/maintain-one-comment@v3
        with:
          body: 感谢 PR。如果有兴趣一起参与维护 Umi，可先用钉钉扫下方二维码（注明 github id）加我钉钉，然后我会拉到群里。<img src="https://img.alicdn.com/imgextra/i2/O1CN01DLiPrU1WsbDdnwRr9_!!6000000002844-2-tps-340-336.png" width="20%"/>
